version: '3.8'

services:
  mongo_db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mongo_db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo:/data/db

  redis:
    container_name: redis
    image: redis:7
    env_file:
      - .env
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  shop_app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: shop_app
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo_db:27017
      - MONGODB_DB=${MONGO_DATABASE}
      - BROKER_URL=${REDIS_URL}
    depends_on:
      - mongo_db

  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: ./scrapers/Dockerfile
    command: "celery -A scrapers.tasks beat --loglevel DEBUG -s /tmp/celerybeat-schedule"
    environment:
     - BROKER_URL=${REDIS_URL}
     - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo_db:27017/
    volumes:
      - ./scrapers:/home/celery/scrapers
    depends_on:
      - redis
      - mongo_db

  celery-worker:
    container_name: celery-worker
    build:
      context: .
      dockerfile: ./scrapers/Dockerfile
    command: "celery -A scrapers.tasks worker --loglevel INFO"
    volumes:
      - ./scrapers:/home/celery/scrapers
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo_db:27017/
      - BROKER_URL=${REDIS_URL}
    depends_on:
      - redis
      - mongo_db
      

volumes:
  mongo:
  redis: