version: '3.8'

services:
  mongo_db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mongo_db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo:/data/db

  shop_app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: shop_app
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo_db:27017/${MONGO_DATABASE}
      - SCRAPERS_URL=http://scrapers:9080/
    depends_on:
      - mongo_db

  scrapers:
    build:
      context: .
      dockerfile: ./scrapers/Dockerfile
    container_name: scrapers
    volumes:
      - ./scrapers:/scrapyrt/project/scrapers
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo_db:27017/${MONGO_DATABASE}
    depends_on:
      - mongo_db
      - redis

  redis:
    container_name: redis
    image: redis:7
    env_file:
      - .env
    command: "redis-server"
    ports:
    - 6379:6379

  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: ./scrapers/Dockerfile.celery
    command: "celery -A celery beat --loglevel DEBUG"
    environment:
     - BROKER_URL=${REDIS_URL}
    volumes:
      - ./scrapers:/home/celery/scrapers
    depends_on:
      - redis

  celery-worker:
    container_name: celery-worker
    build:
      context: .
      dockerfile: ./scrapers/Dockerfile.celery
    depends_on:
      - redis
    command: "celery -A celery worker --loglevel INFO"
    volumes:
      - ./scrapers:/home/celery/scrapers
    environment:
      - BROKER_URL=${REDIS_URL}


volumes:
  mongo: